name: Content Validation

on:
    pull_request:
        paths:
            - "src/content/**"
    push:
        branches: [main]
        paths:
            - "src/content/**"

jobs:
    validate-content:
        name: validate-content
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Validate content
              run: npm run validate-content

            - name: Report success
              if: success()
              run: echo "✅ Content validation passed"

            - name: Report failure
              if: failure()
              run: |
                  echo "❌ Content validation failed"
                  exit 1
